# paperless configuration
PAPERLESS_CONFIG_PATH="$HOME/.config/paperless"
PAPERLESS_EXPORT_PATH="${PAPERLESS_CONFIG_PATH}/export"
PAPERLESS_MANIFEST_PATH="${PAPERLESS_EXPORT_PATH}/manifest.json"
PAPERLESS_HOME_PATH="$HOME/paperless"
PAPERLESS_CONSUME_PATH="${PAPERLESS_HOME_PATH}/consume"
PAPERLESS_INBOX_PATH="${PAPERLESS_CONSUME_PATH}/inbox"
